spring:
  data:
    mongodb:
      database: ${thrive.app.client.id}
      host: ${thrive.db.mongo.host}
      port: 27017
---

spring:
  profiles: "!local"
thrive:
  db:
    mongo:
      host: mongo
---

spring:
  profiles: local
thrive:
  db:
    mongo:
      host: localhost